function rightMostBits(b,d){return b%Math.pow(2,d)|0}function fromBin(b){for(var d=0,e=1,g=b.length-1;0<=g;g--)d+=e*b[g],e*=2;return d}function toBin(b){for(arr=[];0<b;)arr.push(b%2),b=b/2|0;arr.reverse();return arr}function esc(b){"\\"==b&&(b="\\\\");b==chr(0)&&(b="\\"+chr(0));return b}function chr(b){return String.fromCharCode(b)}function range(b){var d=-1,e=-1;for(i in b)if(code=b.charCodeAt(i),32!=code){if(code<d||-1==d)d=code;if(code>e||-1==e)e=code}return[e,d]}
function makeLengthByPrependingZeros(b,d){for(;b.length<d;)b.splice(0,0,0);return b}function makeLengthByAppendingZeros(b,d){for(;b.length<d;)b.push(0);return b}function getNumberOfBits(b){if(0>b)console.log("getNumberOfBits(num, amount) doesn't work with neg num");else{for(bits=0;0<b;)b=b/2|0,bits++;return bits}}function NumberOfBits(b){return getNumberOfBits(b)}
function leftMostBits(b,d,e){if(0==b)return 0;if(0>b)console.log("leftMostBits(num, amount) doesn't work with neg num");else return length=e||getNumberOfBits(b),0>length-d?b:b/Math.pow(2,length-d)|0}function getBit(b,d){return b%Math.pow(2,d)/Math.pow(2,d-1)|0}
function longestChain(b,d){longest=[];if("string"===typeof b[d]){for(;d<b.length&&"string"===typeof b[d];)longest.push(b[d]),d++;return longest}for(n in b[d]){current=number=b[d][n];arr=[];for(var e=d;e<b.length;e++)if(b[e]instanceof Array&&-1!=b[e].indexOf(current))arr.push(current),current+=1;else break;arr.length>longest.length&&(longest=arr)}return longest}
function getB4Locations(b){locations={};for(i in b)b4_word=b[i],void 0!=locations[b4_word]?locations[b4_word].push(parseInt(i)):locations[b4_word]=[parseInt(i)];return locations}function getBits(b,d,e){loc=d/8|0;d%=8;for(a=[];0<e;){var g=Math.min(e,8-d);if(loc>=b.length)return-1;right=rightMostBits(b.charCodeAt(loc),8-d);left=leftMostBits(right,g,8-d);n=makeLengthByPrependingZeros(toBin(left),g);for(i in n)a.push(n[i]);e-=g;d=0;loc++}return a}
function string2bits(b){var d=[];for(s in b)d.push.apply(d,makeLengthByPrependingZeros(toBin(b[s].charCodeAt(0)),8));return d}function BitArray(b){this.uint8=new Uint8Array(b);this.size=0}
BitArray.prototype.add=function(b,d,e){if("number"==typeof b)for(arr=makeLengthByAppendingZeros(toBin(b),1),d?b=e?leftMostBits(b,d):rightMostBits(b,d):d=arr.length,i=0;i<d;i++)console.log(arr[i]),this.uint8[this.size/8|0]+=arr[i]*Math.pow(2,7-this.size%8),this.size++;else if("string"==typeof b)for(i=0;i<b.length;i++)d=makeLengthByPrependingZeros(toBin(b.charCodeAt(i))),this.add(d);else"object"==typeof b&&b.forEach(function(b){this.add(b)})};
BitArray.prototype.get=function(b,d){d|=this.size;arr=[];for(i=b|0;i<d;i++)arr.push(getBit(this.uint8[i/8|0],8-i%8));return arr};BitArray.prototype.toString=function(){str="";for(i=0;i<this.size/8|0;i++)str+=chr(this.uint8[i]);0!=this.size%8&&(last=this.uint8[this.size/8|1],last=fromBin(makeLengthByAppendingZeros(toBin(last),8)),str+=chr(last));return str};BitArray.prototype.toArr=BitArray.prototype.get;function StringStream(b){this.num=0;this.ch="";this.size=0}
StringStream.prototype.add=function(b){this.num+=b*Math.pow(2,7-this.size%8);this.size++;8==this.size&&(this.ch=chr(this.num))};StringStream.prototype.get=function(b){if(b)return 0==this.size?"":chr(this.num);""!=this.ch&&(this.size=this.num=0);b=this.ch;this.ch="";return b};function condense(b,d){converted=[];for(i in b)after_word=b[i],void 0!=d[after_word]?converted.push(d[after_word]):converted.push(after_word);return converted}
function expand(b,d){result="";for(i in b)c=b[i],result=c instanceof Array?result+(d[c[0]]+" "):result+(c+" ");return result.substring(0,result.length-1)}function pack1(b){start=0;for(super_condensed=[];start<b.length;){longest=longestChain(b,start);if(0==longest.length){console.log("longest is 0, that's a problem");break}start+=longest.length;"string"===typeof longest[0]?super_condensed.push(longest.join(" ")):super_condensed.push([longest[0],longest[longest.length-1]])}return super_condensed}
function unpack1(b){unpacked=[];for(i in b)if(p=b[i],p instanceof Array)for(var d=p[0];d<=p[1];d++)unpacked.push([d]);else for(word in words=p.split(" "),words)unpacked.push(words[word]);return unpacked}
function pack2(b){packed="";for(i in b)if(p=b[i],p instanceof Array)for(n in p){start=p[n];num=128;bitsLeft=7;for(chrs="";getNumberOfBits(start)>=bitsLeft;)num+=rightMostBits(start,bitsLeft),start=start/Math.pow(2,bitsLeft)|0,bitsLeft=8,chrs+=esc(chr(num)),num=0;num+=start;0!=num&&(chrs+=esc(chr(num)));packed+=chrs+chr(0)}else{packed+=chr(127);for(part in p)packed+=esc(p[part]);packed+=chr(0)}return packed}
function unpack2(b){e=0;l=[];for(nums=[];e<b.length;){c=b[e];if(c==chr(0)){indicator=nums[0]/128;nums[0]%=128;if(indicator|0){multiplier=1;num=0;for(n in nums)num+=nums[n]*multiplier,multiplier=1==multiplier?128:256*multiplier;l.push(num)}else{str="";for(var d=1;d<nums.length;d++)num=nums[d],str+=chr(num);l.push(str)}nums=[]}else{if("\\"==c){e+=1;if(e>=b.length){console.log("Error, string ends in escape \\");break}c=b[e]}num=c.charCodeAt(0);nums.push(num)}e++}fin=[];for(var e=0;e<l.length;e++)"string"===
typeof l[e]?fin.push(l[e]):(fin.push([l[e],l[e+1]]),e++);return fin}
function zipString(b){var d=[],e=range(b),g=e[1]-1,e=NumberOfBits(1+e[0]-e[1]),m=[];for(i in b)code=b.charCodeAt(i),code=32==code?0:code-g,m.push(code);console.log("-----------------------------------------------------");console.log(m);frequencies={};for(c in m)code=m[c],void 0==frequencies[code]?frequencies[code]=1:frequencies[code]++;tree=[];for(f in frequencies)tree.push([parseInt(frequencies[f]),parseInt(f)]);for(;1<tree.length;)tree.sort(function(b,d){return d[0]-b[0]}),bottom=tree.splice(tree.length-
2),n=[bottom[0][0]+bottom[1][0],[]],n[1].push(bottom[0]),n[1].push(bottom[1]),tree.push(n);tree=tree[0];b=0;for(t=tree;0<t[1].length&&"object"==typeof t[1][0];)t=t[1][0],b++;for(var d=[],q=0;q<b;q++)d.push(0);getNode=function(b,d){t=b;for(p in d)t=t[1][d[p]];return t};var r=[];recorder=function(b,d,e){node=getNode(b,d);"number"==typeof node[1]?r.push(d.slice()):(e.add(0),d=d.slice(),d.push(0),test=JSON.stringify(d),recorder(b,d,e),d[d.length-1]=1,e.add(1),e.add(0),recorder(b,d,e),e.add(1))};message=
new BitArray(1E3);recorder(tree,[],message);d=message.toArr();s=new StringStream;g=chr(g);for(k in d)s.add(d[k]),g+=s.get(!1);b=[];codesCopy=Object.keys(frequencies);codesCopy.sort(function(b,d){return frequencies[d]-frequencies[b]});console.log("codesCopy: "+JSON.stringify(codesCopy));console.log("freq: "+JSON.stringify(frequencies));var h;for(c in codesCopy)h!=codesCopy[c]&&b.push(codesCopy[c]),h=codesCopy[c];h={};for(i in b)h[b[i]]=i;bitSize=e;console.log(JSON.stringify(b));for(c in b){var k=makeLengthByPrependingZeros(toBin(b[c]),
bitSize);for(i in k)s.add(k[i]),g+=s.get(!1)}for(c in m)for(i in k=r[h[m[c]]],k)s.add(k[i]),g+=s.get(!1);k=bitSize*Math.pow(2,5);k+=(8-s.size)%8*Math.pow(2,2);g+=s.get(!0);g+=chr(k);console.log("---------------------------------------------");return g}
function unzipString(b){end=b.charCodeAt(b.length-1);start=b.charCodeAt(0);var d=leftMostBits(end,3),e=rightMostBits(leftMostBits(end,6),3);b=b.substring(1,b.length-1);var g=[];for(h in b)g.push.apply(g,makeLengthByPrependingZeros(toBin(b[h].charCodeAt(0)),8));g.splice(g.length-e,e);var e=h="l",m=0,q=[];b=[];for(var r=0;r<g.length;){bit=g[r];if(0==bit)q.push("l"==h?0:1),h="l";else{0==m&&b.push(q.slice());q.pop();if(0==q.length)if("l"==e)e="r";else break;h="r"}m=bit;r++}r++;var h=r,e=[];for(times=
0;h<g.length&&times<b.length;h+=d,times++){for(var m=[],k=h;k<h+d;k++)m.push(g[k]);e.push(fromBin(m))}console.log(JSON.stringify(e));console.log(JSON.stringify(g.slice(h)));bitsNumerical=[];for(bit in b)bitsNumerical.push([fromBin(b[bit]),b[bit].length]);console.log(JSON.stringify(bitsNumerical));b=d=0;for(m="";h<g.length;){d=2*d+g[h];b++;q=-1;for(k in bitsNumerical)if(bitsNumerical[k][0]==d&&bitsNumerical[k][1]==b){q=k;break}-1!=q&&(console.log(q+", "+e[q]),m+=0==""+e[q]?" ":chr(e[q]+start),b=d=
0);h++}return m};
