function rightMostBits(a,b){return a%Math.pow(2,b)|0}function fromBin(a){for(var b=0,d=1,g=a.length-1;0<=g;g--)b+=d*a[g],d*=2;return b}function toBin(a){for(arr=[];0<a;)arr.push(a%2),a=a/2|0;arr.reverse();return arr}function esc(a){"\\"==a&&(a="\\\\");a==chr(0)&&(a="\\"+chr(0));return a}function chr(a){return String.fromCharCode(a)}function range(a){var b=-1,d=-1;for(i in a)if(code=a.charCodeAt(i),32!=code){if(code<b||-1==b)b=code;if(code>d||-1==d)d=code}return[d,b]}
function makeLengthByPrependingZeros(a,b){for(;a.length<b;)a.splice(0,0,0);return a}function makeLengthByAppendingZeros(a,b){for(;a.length<b;)a.push(0);return a}function getNumberOfBits(a){return toBin(a).length}function NumberOfBits(a){return getNumberOfBits(a)}function leftMostBits(a,b,d){if(0==a)return 0;if(0>a)console.log("leftMostBits(num, amount) doesn't work with neg num");else return length=d||getNumberOfBits(a),0>length-b?a:a/Math.pow(2,length-b)|0}
function getBit(a,b){return a%Math.pow(2,b)/Math.pow(2,b-1)|0}function longestChain(a,b){longest=[];if("string"===typeof a[b]){for(;b<a.length&&"string"===typeof a[b];)longest.push(a[b]),b++;return longest}for(n in a[b]){current=number=a[b][n];arr=[];for(var d=b;d<a.length;d++)if(a[d]instanceof Array&&-1!=a[d].indexOf(current))arr.push(current),current+=1;else break;arr.length>longest.length&&(longest=arr)}return longest}
function getB4Locations(a){locations={};for(i in a)b4_word=a[i],void 0!=locations[b4_word]?locations[b4_word].push(parseInt(i)):locations[b4_word]=[parseInt(i)];return locations}function getBits(a,b,d){loc=b/8|0;b%=8;for(var g=[];0<d;){var h=Math.min(d,8-b);if(loc>=a.length)return-1;right=rightMostBits(a.charCodeAt(loc),8-b);left=leftMostBits(right,h,8-b);b=makeLengthByPrependingZeros(toBin(left),h);for(var e=0;e<b.length;e++)g.push(b[e]);d-=h;b=0;loc++}return g}
function string2bits(a){var b=[];for(s in a)b.push.apply(b,makeLengthByPrependingZeros(toBin(a[s].charCodeAt(0)),8));return b}function BitArray(a){this.uint8=new Uint8Array(a);this.size=0}
BitArray.prototype.add=function(a,b,d){if("number"==typeof a)for(arr=makeLengthByAppendingZeros(toBin(a),1),b?a=d?leftMostBits(a,b):rightMostBits(a,b):b=arr.length,i=0;i<b;i++)console.log(arr[i]),this.uint8[this.size/8|0]+=arr[i]*Math.pow(2,7-this.size%8),this.size++;else if("string"==typeof a)for(i=0;i<a.length;i++)b=makeLengthByPrependingZeros(toBin(a.charCodeAt(i))),this.add(b);else"object"==typeof a&&a.forEach(function(a){this.add(a)})};
BitArray.prototype.get=function(a,b){b|=this.size;arr=[];for(i=a|0;i<b;i++)arr.push(getBit(this.uint8[i/8|0],8-i%8));return arr};BitArray.prototype.toString=function(){str="";for(i=0;i<this.size/8|0;i++)str+=chr(this.uint8[i]);0!=this.size%8&&(last=this.uint8[this.size/8|1],last=fromBin(makeLengthByAppendingZeros(toBin(last),8)),str+=chr(last));return str};BitArray.prototype.toArr=BitArray.prototype.get;function StringStream(a){this.num=0;this.ch="";this.size=0}
StringStream.prototype.add=function(a){this.num+=a*Math.pow(2,7-this.size%8);this.size++;8==this.size&&(this.ch+=chr(this.num),this.num=this.size=0)};StringStream.prototype.addArr=function(a){for(i in a)this.add(a[i])};StringStream.prototype.get=function(a){if(a){if(0==this.size&&0==this.num)return a=this.ch,this.ch="",a;a=this.ch+chr(this.num);this.num=0;this.ch="";this.size=0;return a}a=this.ch;this.ch="";return a};
function condense(a,b){converted=[];for(i in a)after_word=a[i],void 0!=b[after_word]?converted.push(b[after_word]):converted.push(after_word);return converted}function expand(a,b){result="";for(i in a)c=a[i],result=c instanceof Array?result+(b[c[0]]+" "):result+(c+" ");return result.substring(0,result.length-1)}
function pack1(a){start=0;super_condensed=[];for(console.log("C: "+JSON.stringify(a));start<a.length;){longest=longestChain(a,start);if(0==longest.length){console.log("longest is 0, that's a problem");break}console.log(longest);start+=longest.length;"string"===typeof longest[0]?super_condensed.push(longest.join(" ")):super_condensed.push([longest[0],longest[longest.length-1]])}return super_condensed}
function unpack1(a){unpacked=[];for(i in a)if(p=a[i],p instanceof Array)for(var b=p[0];b<=p[1];b++)unpacked.push([b]);else for(word in words=p.split(" "),words)unpacked.push(words[word]);return unpacked}
function pack2(a){packed="";s=new StringStream;var b=-1,d=0,g=-1,h=0,e=[],l=!1;for(m in a){var k=a[m];k instanceof Array?(k[0]==k[1]?(console.log("SA"),e.push([[0,1],!1,!1]),e.push([toBin(b+1+h),!0,!1]),e.push([toBin(k[0]),!0,!1]),e.push([toBin(1),!0,!1]),l=NumberOfBits(Math.max(b+1+h,k[0],1)),l>d&&(d=l),h++):l&&(diff=k[0]-b,0<diff?(diff--,0<diff&&(console.log("D"+diff),e.push([[1,0],!1,!1]),e.push([toBin(b+1+h),!0,!1]),e.push([toBin(diff),!0,!1]),l=NumberOfBits(Math.max(b+1+h,diff)),l>d&&(d=l),h-=
diff)):(diff--,0>diff&&(console.log("A"+diff),e.push([[0,1],!1,!1]),e.push([toBin(b+1+h),!0,!1]),e.push([toBin(k[0]),!0,!1]),e.push([toBin(-diff),!0,!1]),l=NumberOfBits(Math.max(b+1+h,k[0],-diff)),l>d&&(d=l),h-=diff))),b=k[1],b>g&&(g=b),l=!0):(console.log("A"+k),e.push([[1,1],!1,!1]),e.push([toBin(b+1+h),!0,!1]),e.push([toBin(k.length),!0,!0,k]),l=NumberOfBits(Math.max(b+1+h,k.length)),l>d&&(d=l),h+=k.split(" ").length,l=!1)}console.log("size: "+d);packed=chr(d);console.log(JSON.stringify(e));for(var m=
0;m<e.length;m++)toC=e[m],toC[1]?(s.addArr(makeLengthByPrependingZeros(toC[0],d)),packed+=s.get(toC[2]),toC[2]&&(packed+=toC[3])):(s.addArr(toC[0]),packed+=s.get());packed+=s.get(!0);return packed+=chr(g+1)}
function unpack2(a,b){toR=b.slice();size=a.charCodeAt(0);var d=a.charCodeAt(a.length-1);a=a.slice(0,a.length-1);console.log("tot len: "+d);toR=toR.slice(0,d);for(d=8;d<8*a.length;){var g=fromBin(getBits(a,d,2)),d=d+2;console.log("mode: "+g);if(1==g){var h=fromBin(getBits(a,d,size)),d=d+size,e=fromBin(getBits(a,d,size)),d=d+size,l=fromBin(getBits(a,d,size)),d=d+size;console.log("adding ("+e+", "+size+") at "+h+": "+b.slice(e,e+l));toR=toR.slice(0,h).concat(b.slice(e,e+l)).concat(toR.slice(h))}2==g&&
(e=fromBin(getBits(a,d,size)),d+=size,l=fromBin(getBits(a,d,size)),d+=size,console.log("pos: "+e+" length: "+l+" deleting: "+toR.splice(e,l)));3==g&&(e=fromBin(getBits(a,d,size)),d+=size,l=fromBin(getBits(a,d,size)),d+=size,d+=(8-d%8)%8,g=a.slice(d/8,d/8+l),console.log("adding string: "+g),toR=toR.slice(0,e).concat(g.split(" ")).concat(toR.slice(e)),d+=8*l)}return toR.join(" ")}
function zipString(a){var b=[],d=range(a),g=d[1]-1,d=NumberOfBits(1+d[0]-d[1]),h=[];for(i in a)code=a.charCodeAt(i),code=32==code?0:code-g,h.push(code);console.log("-----------------------------------------------------");console.log(h);frequencies={};for(c in h)code=h[c],void 0==frequencies[code]?frequencies[code]=1:frequencies[code]++;tree=[];for(f in frequencies)tree.push([parseInt(frequencies[f]),parseInt(f)]);for(;1<tree.length;)tree.sort(function(a,b){return b[0]-a[0]}),bottom=tree.splice(tree.length-
2),n=[bottom[0][0]+bottom[1][0],[]],n[1].push(bottom[0]),n[1].push(bottom[1]),tree.push(n);tree=tree[0];a=0;for(t=tree;0<t[1].length&&"object"==typeof t[1][0];)t=t[1][0],a++;for(var b=[],e=0;e<a;e++)b.push(0);getNode=function(a,b){t=a;for(p in b)t=t[1][b[p]];return t};var l=[];recorder=function(a,b,d){node=getNode(a,b);"number"==typeof node[1]?l.push(b.slice()):(d.add(0),b=b.slice(),b.push(0),test=JSON.stringify(b),recorder(a,b,d),b[b.length-1]=1,d.add(1),d.add(0),recorder(a,b,d),d.add(1))};message=
new BitArray(1E3);recorder(tree,[],message);b=message.toArr();s=new StringStream;g=chr(g);for(m in b)s.add(b[m]),g+=s.get(!1);a=[];codesCopy=Object.keys(frequencies);codesCopy.sort(function(a,b){return frequencies[b]-frequencies[a]});console.log("codesCopy: "+JSON.stringify(codesCopy));console.log("freq: "+JSON.stringify(frequencies));var k;for(c in codesCopy)k!=codesCopy[c]&&a.push(codesCopy[c]),k=codesCopy[c];k={};for(i in a)k[a[i]]=i;bitSize=d;console.log(JSON.stringify(a));for(c in a){var m=makeLengthByPrependingZeros(toBin(a[c]),
bitSize);for(i in m)s.add(m[i]),g+=s.get(!1)}for(c in h)for(i in m=l[k[h[c]]],m)s.add(m[i]),g+=s.get(!1);m=bitSize*Math.pow(2,5);m+=(8-s.size)%8*Math.pow(2,2);g+=s.get(!0);g+=chr(m);console.log("---------------------------------------------");return g}
function unzipString(a){end=a.charCodeAt(a.length-1);start=a.charCodeAt(0);var b=leftMostBits(end,3),d=rightMostBits(leftMostBits(end,6),3);a=a.substring(1,a.length-1);var g=[];for(k in a)g.push.apply(g,makeLengthByPrependingZeros(toBin(a[k].charCodeAt(0)),8));g.splice(g.length-d,d);var d=k="l",h=0,e=[];a=[];for(var l=0;l<g.length;){bit=g[l];if(0==bit)e.push("l"==k?0:1),k="l";else{0==h&&a.push(e.slice());e.pop();if(0==e.length)if("l"==d)d="r";else break;k="r"}h=bit;l++}l++;var k=l,d=[];for(times=
0;k<g.length&&times<a.length;k+=b,times++){for(var h=[],m=k;m<k+b;m++)h.push(g[m]);d.push(fromBin(h))}console.log(JSON.stringify(d));console.log(JSON.stringify(g.slice(k)));bitsNumerical=[];for(bit in a)bitsNumerical.push([fromBin(a[bit]),a[bit].length]);console.log(JSON.stringify(bitsNumerical));a=b=0;for(h="";k<g.length;){b=2*b+g[k];a++;e=-1;for(m in bitsNumerical)if(bitsNumerical[m][0]==b&&bitsNumerical[m][1]==a){e=m;break}-1!=e&&(console.log(e+", "+d[e]),h+=0==""+d[e]?" ":chr(d[e]+start),a=b=
0);k++}return h}function Minifier(a,b){this.b4=a;this.after=b;this.b4_words=a.split(" ");this.after_words=b.split(" ");this.level=0;this.data=a}Minifier.prototype.condense=function(){this.data=getB4Locations(this.b4_words);this.data=condense(this.after_words,this.data);this.data=pack1(this.data);console.log(this.data);return this.data=pack2(this.data)};Minifier.prototype.uncondense=function(){return this.data=unpack2(this.data,this.b4_words)};Minifier.prototype.getData=function(){return this.data};
